### ISSUE TITLE
How to use with lambda?

### ISSUE THREAD

**Issue by seanhess** [ondrap/dynamodb-generic#4]
Hi there, thanks for your hard work on this. I love the API.

How do you use this with a non-local dynamodb instance? All the examples use localhost:8000. Could you add a link to the README that describes how to connect to dynamodb in production? (I'm using Lambda via serverless)

**Comment by ondrap** [comment]
Just discard the `configure dynamo` from the main example and it should use the production aws.

**Comment by seanhess** [comment]
Neat. Thanks, and the dummy env variables I assume too. I’d still recommend adding a quick note somewhere in the docs but I’m closing. Thank you again
